services:
   mysql:
      image: mysql
      ports:
        - "3306:3306"
      expose:
        - "3306"
      environment:
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=123
        - MYSQL_DATABASE=userservicedb
        - MYSQL_ROOT_PASSWORD=123
      volumes:
        - db_userservice:/var/lib/mysql

volumes:
  db_userservice: